"""Generative proposal engine.

Synthesizes `ProposedModification` instances across multiple `MutationKind`
levels by reading Darwin's own causal model, self-model, world-model
hypotheses, and runtime telemetry. Strategies are registered in a plug-in
registry that the v9 `LiveResearcher` extends dynamically.

The strategies that ship in v6 are intentionally diverse so the
substrate exercises every `MutationKind` level from day one:

  - variable_driven   → RULE proposals (new precondition variables)
  - hypothesis_driven → RULE proposals (hidden-factor probes)
  - loop_starvation   → KERNEL proposals (interval adjustments)
  - consolidation     → RULE proposals (concept-pruning strategies)
  - gate_evolution    → GATE proposals (alternative accept-gate fns)

`SUBSYSTEM` and `MODULE` kinds are reserved for v6.5 (the code-gen layer)
and are not generated by the v6 strategies even though the grammar
supports them.
"""

from __future__ import annotations

import copy
from dataclasses import dataclass
from typing import Any, Callable, Protocol

from darwin.mysterio.meta_gate import GateSpec, default_gate_fn, make_gate_spec
from darwin.mysterio.proposal_spec import ProposalSpec, rule_spec
from darwin.mysterio.safety import MutationKind
from darwin.self_modification import ProposedModification


@dataclass
class MetaProposerContext:
    """The slice of runtime the meta-proposer reads to generate proposals."""

    darwin: Any
    runtime: Any
    recent_outcomes: list[Any]
    last_simulation: dict[str, Any] | None
    last_uncertainty_scan: dict[str, Any] | None


class ProposalStrategy(Protocol):
    name: str

    def __call__(self, ctx: MetaProposerContext) -> list[ProposedModification]:
        ...


class MetaProposer:
    """Plug-in registry of proposal-generation strategies."""

    def __init__(self) -> None:
        self._strategies: dict[str, ProposalStrategy] = {}
        self._seen_signatures: set[str] = set()
        self._register_defaults()

    def register(self, name: str, strategy: Callable[[MetaProposerContext], list[ProposedModification]]) -> None:
        strategy.__name__ = name  # type: ignore[attr-defined]
        strategy.name = name  # type: ignore[attr-defined]
        self._strategies[name] = strategy  # type: ignore[assignment]

    def strategies(self) -> list[str]:
        return list(self._strategies)

    def propose(self, ctx: MetaProposerContext) -> list[ProposedModification]:
        proposals: list[ProposedModification] = []
        for strategy in self._strategies.values():
            try:
                emitted = strategy(ctx)
            except Exception:  # defensive — a bad strategy must not kill the cycle
                continue
            for proposal in emitted:
                spec = getattr(proposal, "spec", None)
                if spec is not None:
                    sig = spec.introspection_signature
                    if sig in self._seen_signatures:
                        continue
                    self._seen_signatures.add(sig)
                proposals.append(proposal)
        return proposals

    def _register_defaults(self) -> None:
        self.register("variable_driven", _strategy_variable_driven)
        self.register("hypothesis_driven", _strategy_hypothesis_driven)
        self.register("loop_starvation", _strategy_loop_starvation)
        self.register("consolidation", _strategy_consolidation)
        self.register("gate_evolution", _strategy_gate_evolution)


# ---------------------------------------------------------------------------
# Strategies
# ---------------------------------------------------------------------------


def _strategy_variable_driven(ctx: MetaProposerContext) -> list[ProposedModification]:
    """Read the worst prediction failure and propose a new precondition rule.

    Currently RULE-class. We attach a derived rule entry to the planner
    overrides under a `derived_rules` dict so it is inspectable, snapshotable,
    and reversible.
    """
    self_model = getattr(ctx.darwin, "self_model", None)
    if self_model is None:
        return []
    failures = getattr(self_model, "prediction_failures", None)
    if not failures:
        return []
    # Top failure
    sorted_failures = sorted(failures.items(), key=lambda item: item[1], reverse=True)
    head_key, head_count = sorted_failures[0]
    if head_count < 2:
        return []

    overrides = _ensure_overrides(ctx.darwin)
    derived = overrides.setdefault("derived_rules", {})
    rule_key = f"precondition::{head_key}"
    if rule_key in derived:
        return []

    old = copy.deepcopy(derived)
    new_rule = {"key": head_key, "kind": "precondition", "weight": min(1.0, 0.2 + 0.1 * head_count)}

    def apply(darwin: Any) -> None:
        overrides2 = _ensure_overrides(darwin)
        derived2 = overrides2.setdefault("derived_rules", {})
        derived2[rule_key] = new_rule

    def revert(darwin: Any) -> None:
        overrides2 = _ensure_overrides(darwin)
        overrides2["derived_rules"] = copy.deepcopy(old)

    spec = rule_spec(
        target_paths=["darwin._planner_overrides.derived_rules"],
        touches={"planner_overrides.derived_rules"},
        description=f"add precondition rule for failing prediction: {head_key}",
        expected_effect="reduce repeat prediction failure on the targeted (action, variable)",
        extra={"rule_key": rule_key, "rule": new_rule},
    )
    proposal = ProposedModification(
        kind=spec.kind.value,
        target=spec.target_paths[0],
        rationale=spec.description,
        apply=apply,
        revert=revert,
        payload={"rule_key": rule_key, "rule": new_rule, "spec": spec.to_record()},
    )
    proposal.spec = spec  # type: ignore[attr-defined]
    return [proposal]


def _strategy_hypothesis_driven(ctx: MetaProposerContext) -> list[ProposedModification]:
    """Pull a high-open-question hypothesis from world_model and register a
    probe sensor for the candidate hidden factor.
    """
    world_model = getattr(ctx.darwin, "world_model", None)
    causal_model = getattr(ctx.darwin, "causal_model", None)
    if world_model is None or causal_model is None:
        return []
    try:
        hypotheses = world_model.hypotheses(causal_model, limit=4)
    except Exception:
        return []
    if not hypotheses:
        return []

    hypothesis = hypotheses[0]
    overrides = _ensure_overrides(ctx.darwin)
    sensors = overrides.setdefault("introspection_sensors", {})
    sensor_key = f"hypothesis::{getattr(hypothesis, 'subject', None) or repr(hypothesis)[:32]}"
    if sensor_key in sensors:
        return []

    old = copy.deepcopy(sensors)
    sensor_payload = {
        "subject": getattr(hypothesis, "subject", None),
        "description": str(hypothesis),
        "registered_at_observations": int(causal_model.total_observations()),
    }

    def apply(darwin: Any) -> None:
        overrides2 = _ensure_overrides(darwin)
        sensors2 = overrides2.setdefault("introspection_sensors", {})
        sensors2[sensor_key] = sensor_payload

    def revert(darwin: Any) -> None:
        overrides2 = _ensure_overrides(darwin)
        overrides2["introspection_sensors"] = copy.deepcopy(old)

    spec = ProposalSpec(
        kind=MutationKind.RULE,
        target_paths=["darwin._planner_overrides.introspection_sensors"],
        touches={"planner_overrides.introspection_sensors"},
        description=f"register introspection sensor for hypothesis: {sensor_payload['description'][:80]}",
        expected_effect="expose a candidate hidden factor as a tracked internal signal",
        extra={"sensor_key": sensor_key},
    )
    proposal = ProposedModification(
        kind=spec.kind.value,
        target=spec.target_paths[0],
        rationale=spec.description,
        apply=apply,
        revert=revert,
        payload={"sensor_key": sensor_key, "sensor": sensor_payload, "spec": spec.to_record()},
    )
    proposal.spec = spec  # type: ignore[attr-defined]
    return [proposal]


def _strategy_loop_starvation(ctx: MetaProposerContext) -> list[ProposedModification]:
    """If a background loop has not produced an event recently, propose an
    interval adjustment.

    Currently KERNEL-class (touches the runtime's loop_intervals dict).
    Operator can roll back via /quarantine.
    """
    runtime = ctx.runtime
    if runtime is None:
        return []
    loop_state = getattr(runtime, "_loop_state", None)
    intervals = getattr(runtime, "loop_intervals", None)
    if not loop_state or not intervals:
        return []

    import time as _time

    now = _time.time()
    starved: list[str] = []
    for name, state in loop_state.items():
        interval = intervals.get(name, 0.0) or 0.0
        if interval <= 0:
            continue
        # runtime.py writes "last_time" (timestamp) and "last_event" (kind);
        # also tolerate "timestamp" for test fixtures.
        last_time = state.get("last_time") or state.get("timestamp") or 0.0
        if last_time and now - last_time > interval * 4:
            starved.append(name)
    if not starved:
        return []

    name = starved[0]
    old_interval = float(intervals.get(name, 0.0))
    new_interval = max(0.5, old_interval * 0.75)
    if abs(new_interval - old_interval) < 1e-6:
        return []

    def apply(darwin: Any, _runtime: Any = runtime, _name: str = name, _new: float = new_interval) -> None:
        _runtime.loop_intervals[_name] = _new

    def revert(darwin: Any, _runtime: Any = runtime, _name: str = name, _old: float = old_interval) -> None:
        _runtime.loop_intervals[_name] = _old

    spec = ProposalSpec(
        kind=MutationKind.KERNEL,
        target_paths=[f"runtime.loop_intervals.{name}"],
        touches={f"loop_intervals.{name}"},
        description=f"shorten starved loop interval: {name} {old_interval:.2f}s → {new_interval:.2f}s",
        expected_effect="reduce starvation by waking the loop more often",
        extra={"loop": name, "old": old_interval, "new": new_interval},
    )
    proposal = ProposedModification(
        kind=spec.kind.value,
        target=spec.target_paths[0],
        rationale=spec.description,
        apply=apply,
        revert=revert,
        payload={"loop": name, "old": old_interval, "new": new_interval, "spec": spec.to_record()},
    )
    proposal.spec = spec  # type: ignore[attr-defined]
    return [proposal]


def _strategy_consolidation(ctx: MetaProposerContext) -> list[ProposedModification]:
    """Register a new consolidation strategy with a tunable parameter
    that affects when low-salience concepts are pruned.
    """
    memory = getattr(ctx.darwin, "memory", None)
    if memory is None:
        return []
    concepts = getattr(memory, "concepts", None)
    if concepts is None:
        return []
    overrides = _ensure_overrides(ctx.darwin)
    strategies = overrides.setdefault("consolidation_strategies", {})
    strategy_key = "salience_threshold_drift"
    if strategy_key in strategies:
        # Adjust the threshold instead.
        old = float(strategies[strategy_key].get("threshold", 0.5))
        new = max(0.1, min(0.9, old + (0.05 if old < 0.5 else -0.05)))
        if abs(new - old) < 1e-6:
            return []
        old_block = copy.deepcopy(strategies)

        def apply(darwin: Any) -> None:
            overrides2 = _ensure_overrides(darwin)
            strategies2 = overrides2.setdefault("consolidation_strategies", {})
            strategies2[strategy_key]["threshold"] = new

        def revert(darwin: Any) -> None:
            overrides2 = _ensure_overrides(darwin)
            overrides2["consolidation_strategies"] = copy.deepcopy(old_block)

        spec = ProposalSpec(
            kind=MutationKind.RULE,
            target_paths=["darwin._planner_overrides.consolidation_strategies.salience_threshold_drift"],
            touches={"planner_overrides.consolidation_strategies"},
            description=f"drift consolidation salience threshold {old:.2f} → {new:.2f}",
            expected_effect="alter rate of low-salience concept pruning",
            extra={"old": old, "new": new},
        )
    else:
        old_block = copy.deepcopy(strategies)
        new_entry = {"threshold": 0.5, "registered_at": int(getattr(ctx.darwin, "_time", 0) or 0)}

        def apply(darwin: Any) -> None:
            overrides2 = _ensure_overrides(darwin)
            strategies2 = overrides2.setdefault("consolidation_strategies", {})
            strategies2[strategy_key] = new_entry

        def revert(darwin: Any) -> None:
            overrides2 = _ensure_overrides(darwin)
            overrides2["consolidation_strategies"] = copy.deepcopy(old_block)

        spec = ProposalSpec(
            kind=MutationKind.RULE,
            target_paths=["darwin._planner_overrides.consolidation_strategies"],
            touches={"planner_overrides.consolidation_strategies"},
            description="register salience-threshold-drift consolidation strategy",
            expected_effect="enable adaptive concept pruning based on salience drift",
            extra={"strategy": strategy_key},
        )

    proposal = ProposedModification(
        kind=spec.kind.value,
        target=spec.target_paths[0],
        rationale=spec.description,
        apply=apply,
        revert=revert,
        payload={"strategy": strategy_key, "spec": spec.to_record()},
    )
    proposal.spec = spec  # type: ignore[attr-defined]
    return [proposal]


def _strategy_gate_evolution(ctx: MetaProposerContext) -> list[ProposedModification]:
    """Occasionally propose an alternative accept gate.

    Emits a GATE proposal at most once per ~10 outcomes so the substrate
    has time to settle between gate swaps.
    """
    runtime = ctx.runtime
    meta_gate = getattr(runtime, "meta_gate", None) if runtime is not None else None
    if meta_gate is None:
        return []
    outcomes = ctx.recent_outcomes or []
    if len(outcomes) < 5:
        return []
    history = meta_gate.history
    if history and len(outcomes) - getattr(history[-1], "shadow_sample_size", 0) < 10:
        return []

    # Derive an alternate gate by tweaking the continuity / visibility weights.
    new_lambda_c = 0.75 if (len(history) % 2 == 0) else 0.25
    new_lambda_v = 0.4 if (len(history) % 2 == 0) else 0.1
    new_fn = default_gate_fn(lambda_continuity=new_lambda_c, lambda_visibility=new_lambda_v)
    new_gate = make_gate_spec(
        new_fn,
        description=(
            f"alt gate: lambda_continuity={new_lambda_c}, lambda_visibility={new_lambda_v}"
        ),
    )
    old_gate_ref = [meta_gate.current]

    def apply(darwin: Any, _runtime: Any = runtime, _new: GateSpec = new_gate) -> None:
        shadow: list[tuple[Any, bool]] = []  # v6: no shadow comparison wiring yet
        _runtime.meta_gate.swap(_new, shadow_outcomes=shadow, notes="proposed by meta_proposer")

    def revert(darwin: Any, _runtime: Any = runtime, _old: list = old_gate_ref) -> None:
        _runtime.meta_gate.swap(_old[0], shadow_outcomes=[], notes="rollback to prior gate")

    spec = ProposalSpec(
        kind=MutationKind.GATE,
        target_paths=["runtime.meta_gate.current"],
        touches={"meta_gate.current"},
        description=new_gate.description,
        expected_effect="alter acceptance behavior of subsequent self-modification cycles",
        extra={"lambda_continuity": new_lambda_c, "lambda_visibility": new_lambda_v},
    )
    proposal = ProposedModification(
        kind=spec.kind.value,
        target=spec.target_paths[0],
        rationale=spec.description,
        apply=apply,
        revert=revert,
        payload={"lambda_continuity": new_lambda_c, "lambda_visibility": new_lambda_v, "spec": spec.to_record()},
    )
    proposal.spec = spec  # type: ignore[attr-defined]
    return [proposal]


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _ensure_overrides(darwin: Any) -> dict[str, Any]:
    overrides = getattr(darwin, "_planner_overrides", None)
    if overrides is None:
        overrides = {}
        setattr(darwin, "_planner_overrides", overrides)
    return overrides
